### ISSUE TITLE
deleteDocument arguments

### ISSUE THREAD

**Issue by mtomic** [webmerge/api-php#1]
Just wondering why we need to pass in the data object into deleteDocument method.  Looking at the class itself $data doesn't get used, which makes sense.  I would think that you would only need to pass in the document ID to delete an existing document.

```
public function deleteDocument($id, $data){
	return $this->request(self::$api_endpoint.'/documents/'.$id, null, 'DELETE');
}
```

**Comment by webmerge** [comment]
@mtomic I think this was just a copy & paste scenario.  We've updated the code and removed the need for that 2nd parameter.  Thanks!
